version: "3"

services:
  caddy-server:
    image: caddy:2
    ports:
      - 8443:8443
    volumes:
      - $PWD/server/caddy.json:/etc/caddy/Caddyfile
      - $PWD/certs:/etc/caddy/keys
  caddy_reverse_proxy:
    image: caddy:2
    ports:
      - 8080:8080
    volumes:
      - $PWD/reverse-proxy/caddy.json:/etc/caddy/Caddyfile
      - $PWD/certs:/etc/caddy/keys
